<?php

require_once dirname(__FILE__) . '/../../../PHP-FamilySearchAPI/FSParse/XMLGEDCOM.php';

/**
 * Test class for XG_Family.
 * Generated by PHPUnit on 2010-11-24 at 14:50:13.
 */
class XG_FamilyTest extends PHPUnit_Framework_TestCase {

    /**
     * @var XG_Family
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new XG_Family;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {

    }

    /**
     * @todo Implement testGetFamGedcom().
     */
    public function testGetFamGedcom() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testToXml().
     */
    public function testToXml() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
?>
